###
# Please keep /.mergify.yml synced!
name: CI

on: [push, pull_request]

jobs:
  main:
    name: >-
      ${{ matrix.os }} ${{ matrix.ruby }}
    runs-on: ${{ matrix.os }}-latest
    env:
      # See https://github.com/tmm1/test-queue#environment-variables
      TEST_QUEUE_WORKERS: 2
    strategy:
      fail-fast: false
      matrix:
        # [ ubuntu, macos, windows ]
        os: [ ubuntu ]
        ruby: [ 2.6, truffleruby-head ]

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: spec
        run: TRUFFLERUBYOPT="--cpusampler" bundle exec rake spec
      # - name: ascii_spec
      #   run:  bundle exec rake ascii_spec
      # - name: internal_investigation
      #   run:  bundle exec rake internal_investigation
